<a href="https://colab.research.google.com/github/AIInspire/Python/blob/main/Numpy_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Write a NumPy program to create an array of 10 zeros, array of 10 ones, and array of 10 fives.

In [ ]:
import numpy as np

zeros_array = np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
ones_array = np.ones(10)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
fives_array = np.full(10, 5)
fives_array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# 2. Write a NumPy program to create an array of all even integers from 30 to 70.

In [ ]:
even_integers = np.arange(30, 71, 2)
even_integers

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

# 3. Write a NumPy program to create an array of given shape (5,6) and integer type, filled with zeros.

In [ ]:
int_array = np.zeros((5, 6), dtype=int)
int_array

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

# 4. Create a 10x10 array with random values and find the minimum and maximum values.

In [ ]:
random_array = np.random.random((10, 10))
random_array

array([[0.95002883, 0.79528728, 0.13276118, 0.48126839, 0.77903682,
        0.97211131, 0.87677207, 0.49914151, 0.08536006, 0.13006426],
       [0.27645376, 0.99547877, 0.88662564, 0.96365148, 0.23618722,
        0.9232274 , 0.15056808, 0.62475816, 0.15721172, 0.49484406],
       [0.18388859, 0.94123084, 0.30935058, 0.4177906 , 0.55704087,
        0.13189949, 0.91825816, 0.35548356, 0.16559927, 0.09260732],
       [0.01510768, 0.31728803, 0.17849367, 0.97486491, 0.52066604,
        0.03878839, 0.69999307, 0.05835699, 0.36738069, 0.77000618],
       [0.18287758, 0.55017837, 0.85755631, 0.54377901, 0.25150992,
        0.206237  , 0.65401012, 0.15270091, 0.8709305 , 0.59470507],
       [0.20656049, 0.906428  , 0.22101894, 0.39355285, 0.88148963,
        0.69288806, 0.0482872 , 0.5318637 , 0.49490611, 0.45617259],
       [0.47638971, 0.05732599, 0.22539331, 0.20143114, 0.66700255,
        0.08929707, 0.07896255, 0.77013203, 0.78187516, 0.3299895 ],
       [0.58889848, 0.36567942, 0.3389168

In [ ]:
random_array.min()

0.015107680305715077

In [ ]:
random_array.max()

0.9954787660423703

# 5. Write a NumPy program to create a 3x3 array with values ranging from 2 to 10.

In [ ]:
array = np.arange(2, 11).reshape(3, 3)
array

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# 6. Write a NumPy program to create an array of size = 20 using arrange, then extract all numbers from a given array greater than 15.

In [ ]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
greater_than_15 = array[array > 15]
greater_than_15

array([16, 17, 18, 19])

# 7. Write a NumPy program to combine the two 2-dimensional arrays using
hstack and vstack.
Array 1: [[0, 1, 3], [5, 7, 9]]
Array 2: [[0, 2, 4], [6, 8, 10]]

In [ ]:
array_1 = np.array([[0, 1, 3], [5, 7, 9]])
array_2 = np.array([[0, 2, 4], [6, 8, 10]])

In [ ]:
np.vstack((array_1, array_2))

array([[ 0,  1,  3],
       [ 5,  7,  9],
       [ 0,  2,  4],
       [ 6,  8, 10]])

In [ ]:
np.hstack((array_1, array_2))

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

# 8. Write a NumPy program to create ones array of size 10 and change the 6th element to 11.

In [ ]:
ones_array = np.ones(10)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
ones_array[5] = 11
ones_array

array([ 1.,  1.,  1.,  1.,  1., 11.,  1.,  1.,  1.,  1.])

# 9. Write a NumPy program to append a value to the end of an array.

In [ ]:
array = np.arange(0, 6)
array

array([0, 1, 2, 3, 4, 5])

In [ ]:
array = np.append(array, 10)
array

array([ 0,  1,  2,  3,  4,  5, 10])

# 10. Write a NumPy program to reverse an array [using two different methods).

In [ ]:
array = np.arange(0, 6)

rev_array_1 = array[::-1]
rev_array_1

array([5, 4, 3, 2, 1, 0])

In [ ]:
array = np.arange(0, 6)

rev_array_2 = array[np.arange(len(array) - 1, -1, -1)]
rev_array_2

array([5, 4, 3, 2, 1, 0])